name: mi_supabase_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.0.0
  firebase_core: ^2.30.0
  cloud_firestore: ^4.17.0
  image_picker: ^1.0.7
  image_picker_for_web: ^2.1.1
  intl: ^0.18.1
  geolocator: ^11.0.0
  url_launcher: ^6.3.0
  cupertino_icons: ^1.0.8
  uuid: ^4.3.3
  flutter_svg: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/always-grey.png
    - assets/images/arabesque.png
    - assets/images/arches.png
    - assets/images/logoApp.svg
